const K="goldStarDay.v12",oldK="goldStarDay.v11",palette=["#e9969a","#e4a15b","#e0b548","#91a66f","#78a58a","#74a3bd","#9a8db2","#c887a6","#e6a984"];
const defaults=[["water","Drink Water","Take 3 sips","#74a3bd","daily",[]],["food","Eat Something","A snack counts","#e4a15b","daily",[]],["teeth","Brush Teeth","Brush for 30 seconds","#e0b548","daily",[]],["fresh","Freshen Up","Wash face or use wipes","#78a58a","daily",[]],["move","Move Your Body","Stand or stretch 1 minute","#e9969a","specific",[1,3,5]],["read","Read","Read one page","#91a66f","anytime",[]]].map(x=>({id:x[0],name:x[1],tiny:x[2],color:x[3],type:x[4],days:x[5]}));
const rewards=[["bookworm","Bookworm","worm","#6f914e"],["lady","Lucky Ladybug","lady","#c65b49"],["bee","Busy Bee","bee","#d8a43f"],["snail","Slow & Steady","snail","#9a7f62"],["butter","Tiny Butterfly","butter","#c788a7"],["flower","Little Bloom","flower","#df8c89"]];
const buddies=[["lady","Ladybug"],["cater","Caterpillar"],["bee","Bee"],["snail","Snail"],["butter","Butterfly"],["beetle","Beetle"]];
const lids=[["sage","#839365"],["strawberry","#d47b78"],["sky","#7d9ead"],["honey","#d6ad58"],["cream","#c7ad86"]],bows=[["rose","#d77979"],["berry","#9b4f55"],["sage","#82916c"],["blue","#7898ac"],["honey","#c99a48"]];
function art(type,color="#789052"){
  const stroke=`stroke="#171513" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"`;
  if(type==="lady")return `<svg viewBox="0 0 120 100" aria-hidden="true"><path d="M14 70Q24 58 43 58Q69 57 105 76Q78 88 40 86Q22 84 14 70Z" fill="#67b94c" ${stroke}/><path d="M24 70Q53 74 89 78M44 62Q39 72 40 82M69 65Q65 75 67 84" fill="none" ${stroke}/><path d="M24 54Q23 25 51 18Q82 12 94 41Q99 53 93 65Q63 74 33 63Z" fill="#f13b35" ${stroke}/><path d="M57 20Q76 29 91 46" fill="none" ${stroke}/><circle cx="43" cy="37" r="7"/><circle cx="67" cy="30" r="8"/><circle cx="75" cy="54" r="8"/><circle cx="45" cy="57" r="7"/><path d="M90 45Q105 42 108 55Q110 69 94 70Q84 68 82 58Q82 49 90 45Z" fill="#171513" ${stroke}/><circle cx="96" cy="53" r="5" fill="white"/><circle cx="106" cy="56" r="5" fill="white"/><circle cx="97" cy="54" r="2"/><circle cx="107" cy="57" r="2"/><path d="M94 44Q96 34 91 28M102 44Q108 35 113 35" fill="none" ${stroke}/></svg>`;
  if(type==="worm"||type==="cater")return `<svg viewBox="0 0 130 95" aria-hidden="true"><path d="M9 77Q13 67 21 71Q26 56 36 66Q43 48 53 62Q63 42 74 59Q84 39 95 57" fill="none" stroke="#66ad3e" stroke-width="20" stroke-linecap="round"/><circle cx="23" cy="69" r="12" fill="#9bd334" ${stroke}/><circle cx="43" cy="61" r="14" fill="#55b94a" ${stroke}/><circle cx="66" cy="58" r="15" fill="#a7dc39" ${stroke}/><circle cx="91" cy="57" r="16" fill="#4db849" ${stroke}/><circle cx="108" cy="52" r="18" fill="#9ed53a" ${stroke}/><circle cx="103" cy="48" r="6" fill="white" ${stroke}/><circle cx="114" cy="47" r="6" fill="white" ${stroke}/><circle cx="104" cy="49" r="2"/><circle cx="115" cy="48" r="2"/><path d="M104 59Q109 64 115 59M103 34Q99 23 94 20M113 34Q116 23 122 21" fill="none" ${stroke}/><circle cx="93" cy="18" r="4" fill="#ffd631" ${stroke}/><circle cx="123" cy="19" r="4" fill="#ffd631" ${stroke}/><path d="M26 80l-3 8M49 74l-1 10M76 73l2 9" fill="none" ${stroke}/></svg>`;
  if(type==="bee")return `<svg viewBox="0 0 120 100" aria-hidden="true"><path d="M45 42Q27 12 14 26Q5 39 31 51" fill="#ccecff" ${stroke}/><path d="M70 38Q89 10 103 24Q113 38 80 51" fill="#e2d9f5" ${stroke}/><ellipse cx="59" cy="57" rx="31" ry="22" fill="#ffd629" ${stroke}/><path d="M43 38Q36 55 42 73M59 35Q52 55 59 78M76 40Q70 56 76 72" fill="none" ${stroke}/><circle cx="53" cy="43" r="11" fill="white" ${stroke}/><circle cx="72" cy="45" r="11" fill="white" ${stroke}/><circle cx="55" cy="45" r="3"/><circle cx="73" cy="47" r="3"/><path d="M57 60Q64 66 71 59M48 33Q46 22 42 18M75 34Q79 23 85 20" fill="none" ${stroke}/><circle cx="41" cy="17" r="4" fill="#ffd629" ${stroke}/><circle cx="86" cy="19" r="4" fill="#ffd629" ${stroke}/><path d="M90 58l12 5-11 5" fill="#171513" ${stroke}/></svg>`;
  if(type==="snail")return `<svg viewBox="0 0 125 100" aria-hidden="true"><path d="M15 79Q37 70 60 75Q83 78 110 80Q101 90 72 89H31Q18 88 15 79Z" fill="#e9c9ed" ${stroke}/><path d="M37 77Q44 65 43 47Q42 32 49 26Q56 23 58 36L59 58" fill="#e9c9ed" ${stroke}/><path d="M49 28Q44 18 39 15M55 27Q57 16 63 13" fill="none" ${stroke}/><circle cx="39" cy="14" r="4" fill="#171513"/><circle cx="64" cy="13" r="4" fill="#171513"/><circle cx="50" cy="38" r="3"/><circle cx="58" cy="39" r="3"/><path d="M50 49Q55 54 61 49" fill="none" ${stroke}/><circle cx="82" cy="55" r="29" fill="#ffd23f" ${stroke}/><path d="M83 37Q102 39 101 56Q100 72 82 72Q67 72 66 58Q65 45 78 44Q89 43 91 53Q92 62 83 63Q76 64 75 57" fill="none" ${stroke}/></svg>`;
  if(type==="butter")return `<svg viewBox="0 0 120 100" aria-hidden="true"><path d="M54 48Q32 8 13 18Q0 31 16 54Q27 67 49 58Z" fill="#f2443e" ${stroke}/><path d="M66 48Q88 8 107 18Q120 31 104 54Q93 67 71 58Z" fill="#f2443e" ${stroke}/><path d="M53 57Q29 58 21 76Q21 91 42 86Q54 82 59 66Z" fill="#f2443e" ${stroke}/><path d="M67 57Q91 58 99 76Q99 91 78 86Q66 82 61 66Z" fill="#f2443e" ${stroke}/><ellipse cx="60" cy="55" rx="10" ry="28" fill="#2d83d5" ${stroke}/><path d="M56 29Q50 15 44 12M64 29Q70 15 77 12" fill="none" ${stroke}/><path d="M25 35Q33 25 41 36Q33 49 25 35ZM79 36Q87 25 95 35Q87 49 79 36Z" fill="#f4a3c6" ${stroke}/><circle cx="37" cy="70" r="5" fill="#fff4cf"/><circle cx="84" cy="70" r="5" fill="#fff4cf"/><circle cx="56" cy="43" r="5" fill="white" ${stroke}/><circle cx="66" cy="43" r="5" fill="white" ${stroke}/></svg>`;
  if(type==="beetle")return `<svg viewBox="0 0 110 105" aria-hidden="true"><path d="M41 25Q34 12 28 9M68 25Q76 12 84 10" fill="none" ${stroke}/><path d="M34 28Q55 14 76 29Q89 44 83 72Q77 94 55 96Q32 94 26 72Q20 45 34 28Z" fill="#35b98a" ${stroke}/><path d="M55 24V94" fill="none" ${stroke}/><path d="M33 46Q42 34 53 37V83Q39 83 31 70Q27 57 33 46Z" fill="#6b9de8" ${stroke}/><path d="M77 46Q68 34 57 37V83Q71 83 79 70Q83 57 77 46Z" fill="#7fa6ef" ${stroke}/><circle cx="47" cy="30" r="8" fill="white" ${stroke}/><circle cx="64" cy="30" r="8" fill="white" ${stroke}/><circle cx="49" cy="31" r="3"/><circle cx="66" cy="31" r="3"/><path d="M24 48L11 40M23 61L9 63M29 76L17 86M86 48L99 40M87 61L101 63M81 76L93 86" fill="none" ${stroke}/><circle cx="41" cy="53" r="5" fill="#f6a5bd"/><circle cx="69" cy="61" r="5" fill="#ffd05d"/><path d="M38 53h6M41 50v6M66 61h6M69 58v6" ${stroke}/></svg>`;
  if(type==="flower")return `<svg viewBox="0 0 100 100"><path d="M50 50v42M50 73c-16-12-24-4-22 3 3 9 15 7 22 2M50 67c16-12 24-4 22 3-3 9-15 7-22 2" fill="${color}" ${stroke}/><circle cx="50" cy="38" r="11" fill="#d7a84c"/><circle cx="50" cy="18" r="16" fill="${color}"/><circle cx="70" cy="36" r="16" fill="${color}"/><circle cx="30" cy="36" r="16" fill="${color}"/><circle cx="50" cy="56" r="16" fill="${color}"/></svg>`;
  return `<svg viewBox="0 0 100 100"><ellipse cx="50" cy="55" rx="27" ry="33" fill="${color}" ${stroke}/><path d="M50 22v66" ${stroke}/></svg>`
}
function fresh(){return{habits:defaults,days:{},bare:false,pfp:"lady",jarName:"Gertrude",jar:{lid:"sage",bow:"rose",placed:[]},unlocked:[],challenges:[{id:"books",name:"read 10 books",goal:10,progress:0,reward:"bookworm"}],settings:{morning:"09:00",evening:"19:00"}}}
function load(){try{let v=JSON.parse(localStorage.getItem(K)||"null");if(v)return {...fresh(),...v};let old=JSON.parse(localStorage.getItem(oldK)||"null");return old?{...fresh(),...old,pfp:"lady",unlocked:old.custom||[],challenges:(old.challenges||[]).map((c,i)=>({...c,reward:rewards[i%rewards.length][0]}))}:fresh()}catch{return fresh()}}
let s=load(),view=new Date(),chosen=palette[0],chosenDays=[],picked=null,chosenReward=rewards[0][0];view.setDate(1);const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
function save(){localStorage.setItem(K,JSON.stringify(s))}function key(d=new Date()){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}function getDay(d=new Date()){return s.days[key(d)]||(s.days[key(d)]={done:{}})}function total(){return Object.values(s.days).reduce((n,d)=>n+Object.keys(d.done||{}).length,0)}function growth(){return Object.values(s.days).filter(d=>Object.keys(d.done||{}).length).length}function due(h){return h.type==="daily"||h.type==="anytime"||h.days.includes(new Date().getDay())}function esc(v){return String(v).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function rewardObj(id){let r=rewards.find(x=>x[0]===id);return r?{id:r[0],name:r[1],type:r[2],color:r[3]}:null}function allUnlocked(){return s.unlocked.map(x=>typeof x==="string"?rewardObj(x):x).filter(Boolean)}
function render(){let done=getDay().done;$("#todayGrowth").textContent=Object.keys(done).length?"+1%":"+0%";$("#bare").checked=s.bare;$("#jarName").textContent=s.jarName;$("#starTotal").textContent=total();$("#growthDays").textContent=growth();$("#progressStars").textContent=total();$("#morning").value=s.settings.morning;$("#evening").value=s.settings.evening;renderPfp();renderHabits();renderCalendar();renderJar();renderBars();renderChallenges();renderStickers();renderDress();save()}
function renderPfp(){let type=s.pfp==="cater"?"cater":s.pfp;$("#pfp").innerHTML=art(type,s.pfp==="lady"?"#c65b49":s.pfp==="bee"?"#d8a43f":s.pfp==="butter"?"#c788a7":"#789052");let g=$("#pfpGrid");g.innerHTML="";buddies.forEach(b=>{let e=document.createElement("button");e.className="buddy"+(s.pfp===b[0]?" selected":"");e.innerHTML=art(b[0],b[0]==="lady"?"#c65b49":b[0]==="bee"?"#d8a43f":b[0]==="butter"?"#c788a7":"#789052")+`<small>${b[1]}</small>`;e.onclick=()=>{s.pfp=b[0];closeAll();render()};g.append(e)})}
function renderHabits(){let box=$("#habitList"),done=getDay().done;box.innerHTML="";let hs=s.habits.filter(due);if(s.bare)hs=hs.slice(0,3);hs.forEach(h=>{let e=document.createElement("div");e.className="habit";e.innerHTML=`<div class="star" style="color:${h.color}">★</div><div><b>${esc(h.name)}</b><small>${esc(s.bare?h.tiny:h.type==="daily"?"every day":h.type==="anytime"?"whenever":h.days.map(n=>"SMTWTFS"[n]).join(" · "))}</small></div><button data-do="${h.id}" class="check ${done[h.id]?"done":""}">${done[h.id]?"✓":""}</button>`;box.append(e)});$$("[data-do]").forEach(b=>b.onclick=()=>{let h=s.habits.find(x=>x.id===b.dataset.do),d=getDay();d.done[h.id]?delete d.done[h.id]:d.done[h.id]={color:h.color,name:h.name};render()})}
function renderCalendar(){$("#monthTitle").textContent=new Intl.DateTimeFormat(undefined,{month:"long",year:"numeric"}).format(view);let box=$("#calendarGrid");box.innerHTML="",first=new Date(view.getFullYear(),view.getMonth(),1),start=new Date(view.getFullYear(),view.getMonth(),1-first.getDay()),mg=0;for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let vals=Object.values(getDay(d).done||{});if(d.getMonth()===view.getMonth()&&vals.length)mg++;let e=document.createElement("div");e.className="day"+(d.getMonth()!=view.getMonth()?" other":"")+(key(d)===key()?" today":"")+(vals.length?" haswins":"");e.innerHTML=`<b>${d.getDate()}</b><div class="daystars"></div>`;vals.slice(0,8).forEach(v=>{let x=document.createElement("i");x.textContent="★";x.style.color=v.color;e.querySelector(".daystars").append(x)});e.onclick=()=>showDay(d);box.append(e)}$("#monthGrowth").textContent=`+${mg}% growth`;let stages=["· · ·","⌁ · ·","⌁ ♧ ·","♧ ✿ ♧","✿ ♧ ✿ ♧"];$("#gardenStage").textContent=stages[Math.min(4,Math.floor(mg/5))]}
function showDay(d){$("#dayTitle").textContent=new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric"}).format(d);let vals=Object.values(getDay(d).done||{}),box=$("#dayWins");box.innerHTML=vals.length?vals.map(v=>`<div class="day-win"><span class="dot" style="color:${v.color}">★</span><b>${esc(v.name||"little win")}</b></div>`).join(""):`<p class="sub">A quiet day. Nothing was lost.</p>`;open("day")}
function renderJar(){let l=lids.find(x=>x[0]===s.jar.lid)||lids[0],b=bows.find(x=>x[0]===s.jar.bow)||bows[0];$("#jarLid").style.background=l[1];$("#jarBow").style.color=b[1];let box=$("#jarStars");box.innerHTML="";Object.values(s.days).flatMap(d=>Object.values(d.done||{})).slice(-90).forEach(v=>{let x=document.createElement("span");x.textContent="★";x.style.color=v.color;box.append(x)});let p=$("#placedStickers");p.innerHTML="";s.jar.placed.forEach((x,i)=>{let st=rewardObj(x.id)||allUnlocked().find(z=>z.id===x.id);if(!st)return;let e=document.createElement("span");e.className="placed";e.innerHTML=art(st.type,st.color);e.style.width="55px";e.style.height="55px";e.style.left=x.x+"%";e.style.top=x.y+"%";e.onclick=ev=>{ev.stopPropagation();s.jar.placed.splice(i,1);render()};p.append(e)})}
function renderBars(){let box=$("#bars");box.innerHTML="";s.habits.forEach(h=>{let n=Object.values(s.days).filter(d=>d.done&&d.done[h.id]).length;box.innerHTML+=`<div class="barrow"><span>${esc(h.name)}</span><div class="bar"><i style="width:${Math.min(100,n*10)}%;background:${h.color}"></i></div><b>${n}</b></div>`})}
function renderChallenges(){let box=$("#challenges");box.innerHTML="";s.challenges.forEach(c=>{let r=rewardObj(c.reward)||rewardObj("flower"),won=c.progress>=c.goal,e=document.createElement("div");e.className="challenge";e.innerHTML=`<div class="reward-preview ${won?"":"locked"}">${art(r.type,r.color)}</div><div><b>${esc(c.name)}</b><br><small>${c.progress}/${c.goal} · reward: ${r.name}</small><div class="bar"><i style="width:${Math.min(100,c.progress/c.goal*100)}%;background:${r.color}"></i></div>${won?`<small>♡ sticker unlocked!</small>`:`<button data-c="${c.id}">+1 progress</button>`}</div>`;box.append(e)});$$("[data-c]").forEach(b=>b.onclick=()=>{let c=s.challenges.find(x=>x.id===b.dataset.c);c.progress=Math.min(c.goal,c.progress+1);if(c.progress===c.goal&&!s.unlocked.some(x=>(typeof x==="string"?x:x.id)===c.reward))s.unlocked.push(c.reward);render()})}
function renderStickers(){let box=$("#stickerGrid"),un=allUnlocked();box.innerHTML="";rewards.forEach(r=>{let ok=un.some(x=>x.id===r[0]),e=document.createElement("button");e.className="sticker"+(ok?"":" locked");e.innerHTML=art(r[2],r[3])+`<b>${r[1]}</b><small>${ok?"tap to place":"complete a challenge to unlock"}</small>`;if(ok)e.onclick=()=>{picked=r[0];closeAll();tab("jar")};box.append(e)})}
function renderDress(){let a=$("#lidGrid"),b=$("#bowGrid");a.innerHTML="",b.innerHTML="";lids.forEach(x=>{let q=document.createElement("button");q.className="option"+(s.jar.lid===x[0]?" selected":"");q.textContent=x[0];q.onclick=()=>{s.jar.lid=x[0];render()};a.append(q)});bows.forEach(x=>{let q=document.createElement("button");q.className="option"+(s.jar.bow===x[0]?" selected":"");q.innerHTML=`<span style="color:${x[1]}">♡</span><br>${x[0]}`;q.onclick=()=>{s.jar.bow=x[0];render()};b.append(q)})}
function tab(id){$$("nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id));scrollTo(0,0)}$$("nav button").forEach(b=>b.onclick=()=>tab(b.dataset.tab));function open(id){$("#"+id+"Modal").classList.add("show")}function closeAll(){$$(".modal").forEach(x=>x.classList.remove("show"))}$$(".close").forEach(x=>x.onclick=closeAll);$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)closeAll()})
$("#pfp").onclick=()=>open("pfp");$("#bare").onchange=e=>{s.bare=e.target.checked;render()};$("#prev").onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1);renderCalendar()};$("#next").onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1);renderCalendar()}
function picker(){let p=$("#colorPicker");p.innerHTML="";palette.forEach(c=>{let b=document.createElement("button");b.className="swatch"+(c===chosen?" selected":"");b.style.background=c;b.onclick=()=>{chosen=c;$("#customColor").value=c;picker()};p.append(b)});let d=$("#dayPicker");d.innerHTML="";[0,1,2,3,4,5,6].forEach(n=>{let b=document.createElement("button");b.textContent="SMTWTFS"[n];if(chosenDays.includes(n))b.className="selected";b.onclick=e=>{e.preventDefault();chosenDays.includes(n)?chosenDays=chosenDays.filter(x=>x!==n):chosenDays.push(n);picker()};d.append(b)})}
function habitForm(h=null){$("#habitModalTitle").textContent=h?"edit habit":"create a habit";$("#editHabitId").value=h?.id||"";$("#habitName").value=h?.name||"";$("#habitTiny").value=h?.tiny||"";chosen=h?.color||palette[0];$("#customColor").value=chosen;$("#schedule").value=h?.type||"daily";chosenDays=[...(h?.days||[])];$("#dayPicker").classList.toggle("hidden",$("#schedule").value!=="specific");picker();open("habit")}
$("#addHabit").onclick=()=>habitForm();$("#customColor").oninput=e=>{chosen=e.target.value;picker()};$("#schedule").onchange=e=>$("#dayPicker").classList.toggle("hidden",e.target.value!=="specific");$("#saveHabit").onclick=()=>{let n=$("#habitName").value.trim(),type=$("#schedule").value,id=$("#editHabitId").value;if(!n)return alert("Give your habit a name.");if(type==="specific"&&!chosenDays.length)return alert("Pick at least one day.");let obj={id:id||"h"+Date.now(),name:n,tiny:$("#habitTiny").value.trim()||"A tiny version counts",color:chosen,type,days:[...chosenDays]};if(id)s.habits=s.habits.map(h=>h.id===id?obj:h);else s.habits.push(obj);closeAll();render()}
$("#jarDrop").onclick=e=>{if(!picked)return;let r=$("#jarDrop").getBoundingClientRect();s.jar.placed.push({id:picked,x:Math.max(15,Math.min(85,(e.clientX-r.left)/r.width*100)),y:Math.max(20,Math.min(88,(e.clientY-r.top)/r.height*100))});picked=null;render()};$("#stickersBtn").onclick=()=>open("sticker");$("#dressBtn").onclick=()=>open("dress");$("#renameJar").onclick=()=>{$("#jarNameInput").value=s.jarName;open("rename")};$("#saveJarName").onclick=()=>{if($("#jarNameInput").value.trim())s.jarName=$("#jarNameInput").value.trim();closeAll();render()}
function rewardPicker(){let g=$("#rewardGrid");g.innerHTML="";rewards.forEach(r=>{let e=document.createElement("button");e.className="reward"+(chosenReward===r[0]?" selected":"");e.innerHTML=art(r[2],r[3])+`<b>${r[1]}</b>`;e.onclick=()=>{chosenReward=r[0];rewardPicker()};g.append(e)})}
$("#addChallenge").onclick=()=>{chosenReward=rewards[0][0];rewardPicker();open("challenge")};$("#saveChallenge").onclick=()=>{let n=$("#challengeName").value.trim(),g=Math.max(1,+$("#challengeGoal").value||1);if(!n)return alert("Name your challenge.");s.challenges.push({id:"c"+Date.now(),name:n,goal:g,progress:0,reward:chosenReward});$("#challengeName").value="";closeAll();render()}
function manage(){let box=$("#manageList");box.innerHTML="";s.habits.forEach(h=>{let e=document.createElement("div");e.className="manage-row";e.innerHTML=`<div><b>${esc(h.name)}</b><small><span style="color:${h.color}">★</span> ${esc(h.tiny)}</small></div><div class="manage-actions"><button data-edit="${h.id}">edit</button><button data-del="${h.id}">delete</button></div>`;box.append(e)});$$("[data-edit]").forEach(b=>b.onclick=()=>{closeAll();habitForm(s.habits.find(x=>x.id===b.dataset.edit))});$$("[data-del]").forEach(b=>b.onclick=()=>{s.habits=s.habits.filter(x=>x.id!==b.dataset.del);manage();render()});open("manage")}$("#manageHabits").onclick=manage;
$("#morning").onchange=e=>{s.settings.morning=e.target.value;save()};$("#evening").onchange=e=>{s.settings.evening=e.target.value;save()};$("#testNotification").onclick=async()=>{if(!("Notification"in window))return alert("Notifications aren't available here.");let p=await Notification.requestPermission();if(p==="granted")new Notification("gold star day ♡",{body:"One tiny thing counts. Your stars are still here."})}
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));render();