const K="goldStarDay.v11", palette=["#e9969a","#e4a15b","#e0b548","#91a66f","#78a58a","#74a3bd","#9a8db2","#c887a6","#e6a984"];
const defaults=[["water","Drink Water","Take 3 sips","#74a3bd","daily",[]],["food","Eat Something","A snack counts","#e4a15b","daily",[]],["teeth","Brush Teeth","Brush for 30 seconds","#e0b548","daily",[]],["fresh","Freshen Up","Wash face or use wipes","#78a58a","daily",[]],["move","Move Your Body","Stand or stretch 1 minute","#e9969a","specific",[1,3,5]],["read","Read","Read one page","#91a66f","anytime",[]]].map(x=>({id:x[0],name:x[1],tiny:x[2],color:x[3],type:x[4],days:x[5]}));
const stickerDefs=[["first","first little win","★",1,"#e0b548"],["club","1% club","1%",7,"#91a66f"],["book","book worm","▤",15,"#c887a6"],["heart","soft heart","♥",25,"#e9969a"],["flower","little bloom","✿",35,"#e4a15b"],["lady","ladybug","●",50,"#dc654b"],["sun","sunny day","☼",75,"#e0b548"]].map(x=>({id:x[0],name:x[1],art:x[2],need:x[3],color:x[4]}));
const lids=[["green","repeating-linear-gradient(90deg,#78924f 0 15px,#f8f0dc 15px 30px)"],["pink","repeating-linear-gradient(90deg,#d98e8c 0 15px,#f8f0dc 15px 30px)"],["blue","repeating-linear-gradient(90deg,#7d9fb0 0 15px,#f8f0dc 15px 30px)"],["gold","repeating-linear-gradient(90deg,#d9b55e 0 15px,#f8f0dc 15px 30px)"]], bows=[["pink","#d87978"],["red","#b95f4f"],["sage","#82916c"],["blue","#7898ac"],["cream","#c7ad86"]];
function fresh(){return{habits:defaults,days:{},bare:false,jarName:"Gertrude",jar:{lid:"green",bow:"pink",placed:[]},custom:[],challenges:[{id:"books",name:"read 10 books",goal:10,progress:0}],settings:{morning:"09:00",evening:"19:00"}}}
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(K)||"null")}}catch{return fresh()}}let s=load(),view=new Date(),chosen=palette[0],chosenDays=[],picked=null;view.setDate(1);
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];function save(){localStorage.setItem(K,JSON.stringify(s))}function key(d=new Date()){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}function dd(d=new Date()){return s.days[key(d)]||(s.days[key(d)]={done:{}})}function total(){return Object.values(s.days).reduce((n,d)=>n+Object.keys(d.done||{}).length,0)}function growthDays(){return Object.values(s.days).filter(d=>Object.keys(d.done||{}).length).length}function due(h){return h.type==="daily"||h.type==="anytime"||h.days.includes(new Date().getDay())}function esc(v){return String(v).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function render(){let done=dd().done;$("#todayGrowth").textContent=Object.keys(done).length?"+1%":"+0%";$("#bare").checked=s.bare;$("#jarName").textContent=s.jarName;$("#starTotal").textContent=total();$("#growthDays").textContent=growthDays();$("#progressStars").textContent=total();$("#morning").value=s.settings.morning;$("#evening").value=s.settings.evening;renderHabits();renderCalendar();renderJar();renderBars();renderChallenges();renderStickers();renderDress();save()}
function renderHabits(){let box=$("#habitList"),done=dd().done;box.innerHTML="";let hs=s.habits.filter(due);if(s.bare)hs=hs.slice(0,3);hs.forEach(h=>{let e=document.createElement("div");e.className="habit";e.innerHTML=`<div class="star" style="color:${h.color}">★</div><div><b>${esc(h.name)}</b><small>${esc(s.bare?h.tiny:h.type==="daily"?"every day":h.type==="anytime"?"whenever":h.days.map(n=>"SMTWTFS"[n]).join(" · "))}</small></div><button data-do="${h.id}" class="check ${done[h.id]?"done":""}">${done[h.id]?"✓":""}</button>`;box.append(e)});$$("[data-do]").forEach(b=>b.onclick=()=>{let h=s.habits.find(x=>x.id===b.dataset.do),d=dd();if(d.done[h.id])delete d.done[h.id];else d.done[h.id]={color:h.color};render()})}
function renderCalendar(){$("#monthTitle").textContent=new Intl.DateTimeFormat(undefined,{month:"long",year:"numeric"}).format(view);let box=$("#calendarGrid");box.innerHTML="";let first=new Date(view.getFullYear(),view.getMonth(),1),start=new Date(view.getFullYear(),view.getMonth(),1-first.getDay());for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let e=document.createElement("div");e.className="day"+(d.getMonth()!=view.getMonth()?" other":"")+(key(d)===key()?" today":"");e.innerHTML=`<b>${d.getDate()}</b><div class="daystars"></div>`;Object.values(dd(d).done||{}).forEach(v=>{let x=document.createElement("i");x.textContent="★";x.style.color=v.color;e.querySelector(".daystars").append(x)});box.append(e)}let mg=Object.entries(s.days).filter(([k,v])=>{let d=new Date(k+"T12:00:00");return d.getMonth()===view.getMonth()&&d.getFullYear()===view.getFullYear()&&Object.keys(v.done||{}).length}).length;$("#monthGrowth").textContent=`+${mg}% growth this month`}
function renderJar(){let l=lids.find(x=>x[0]===s.jar.lid)||lids[0],b=bows.find(x=>x[0]===s.jar.bow)||bows[0];$("#jarLid").style.background=l[1];$("#jarBow").style.color=b[1];let box=$("#jarStars");box.innerHTML="";Object.values(s.days).flatMap(d=>Object.values(d.done||{})).slice(-90).forEach(v=>{let x=document.createElement("span");x.textContent="★";x.style.color=v.color;box.append(x)});let p=$("#placedStickers");p.innerHTML="";s.jar.placed.forEach((x,i)=>{let st=[...stickerDefs,...s.custom].find(z=>z.id===x.id);if(!st)return;let e=document.createElement("span");e.className="placed";e.textContent=st.art;e.style.color=st.color;e.style.left=x.x+"%";e.style.top=x.y+"%";e.onclick=ev=>{ev.stopPropagation();s.jar.placed.splice(i,1);render()};p.append(e)})}
function renderBars(){let box=$("#bars");box.innerHTML="";s.habits.forEach(h=>{let n=Object.values(s.days).filter(d=>d.done&&d.done[h.id]).length;box.innerHTML+=`<div class="barrow"><span>${esc(h.name)}</span><div class="bar"><i style="width:${Math.min(100,n*10)}%;background:${h.color}"></i></div><b>${n}</b></div>`})}
function renderChallenges(){let box=$("#challenges");box.innerHTML="";s.challenges.forEach(c=>{let e=document.createElement("div");e.className="challenge";e.innerHTML=`<b>${esc(c.name)}</b> <small>${c.progress}/${c.goal}</small><br><button data-c="${c.id}">+1 progress</button>`;box.append(e)});$$("[data-c]").forEach(b=>b.onclick=()=>{let c=s.challenges.find(x=>x.id===b.dataset.c);c.progress=Math.min(c.goal,c.progress+1);if(c.progress===c.goal&&!s.custom.some(x=>x.id==="reward"+c.id))s.custom.push({id:"reward"+c.id,name:c.name,art:"✿",color:"#e9969a"});render()})}
function renderStickers(){let box=$("#stickerGrid"),t=total();box.innerHTML="";[...stickerDefs,...s.custom].forEach(st=>{let ok=!st.need||t>=st.need,e=document.createElement("button");e.className="sticker"+(ok?"":" locked");e.innerHTML=`<span style="color:${st.color}">${st.art}</span><b>${esc(st.name)}</b><small>${ok?"tap to add to jar":`unlock at ${st.need} stars`}</small>`;if(ok)e.onclick=()=>{picked=st.id;closeAll();tab("jar")};box.append(e)})}
function renderDress(){let a=$("#lidGrid"),b=$("#bowGrid");a.innerHTML="";b.innerHTML="";lids.forEach(x=>{let q=document.createElement("button");q.className="option"+(s.jar.lid===x[0]?" selected":"");q.textContent=x[0];q.onclick=()=>{s.jar.lid=x[0];render()};a.append(q)});bows.forEach(x=>{let q=document.createElement("button");q.className="option"+(s.jar.bow===x[0]?" selected":"");q.innerHTML=`<span style="color:${x[1]}">୨୧</span><br>${x[0]}`;q.onclick=()=>{s.jar.bow=x[0];render()};b.append(q)})}
function tab(id){$$("nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id));scrollTo(0,0)}$$("nav button").forEach(b=>b.onclick=()=>tab(b.dataset.tab));function open(id){$("#"+id+"Modal").classList.add("show")}function closeAll(){$$(".modal").forEach(x=>x.classList.remove("show"))}$$(".close").forEach(x=>x.onclick=closeAll);$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)closeAll()})
$("#bare").onchange=e=>{s.bare=e.target.checked;render()};$("#prev").onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1);renderCalendar()};$("#next").onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1);renderCalendar()}
function picker(){let p=$("#colorPicker");p.innerHTML="";palette.forEach(c=>{let b=document.createElement("button");b.className="swatch"+(c===chosen?" selected":"");b.style.background=c;b.onclick=()=>{chosen=c;picker()};p.append(b)});let d=$("#dayPicker");d.innerHTML="";[0,1,2,3,4,5,6].forEach(n=>{let b=document.createElement("button");b.textContent="SMTWTFS"[n];if(chosenDays.includes(n))b.className="selected";b.onclick=e=>{e.preventDefault();chosenDays.includes(n)?chosenDays=chosenDays.filter(x=>x!==n):chosenDays.push(n);picker()};d.append(b)})}
$("#addHabit").onclick=()=>{chosen=palette[0];chosenDays=[];picker();open("habit")};$("#schedule").onchange=e=>$("#dayPicker").classList.toggle("hidden",e.target.value!=="specific");$("#saveHabit").onclick=()=>{let n=$("#habitName").value.trim(),type=$("#schedule").value;if(!n)return alert("Give your habit a name.");if(type==="specific"&&!chosenDays.length)return alert("Pick at least one day.");s.habits.push({id:"h"+Date.now(),name:n,tiny:$("#habitTiny").value.trim()||"A tiny version counts",color:chosen,type,days:[...chosenDays]});$("#habitName").value="";$("#habitTiny").value="";closeAll();render()}
$("#jarDrop").onclick=e=>{if(!picked)return;let r=$("#jarDrop").getBoundingClientRect();s.jar.placed.push({id:picked,x:Math.max(15,Math.min(85,(e.clientX-r.left)/r.width*100)),y:Math.max(20,Math.min(88,(e.clientY-r.top)/r.height*100))});picked=null;render()};$("#stickersBtn").onclick=()=>open("sticker");$("#dressBtn").onclick=()=>open("dress");$("#renameJar").onclick=()=>{$("#jarNameInput").value=s.jarName;open("rename")};$("#saveJarName").onclick=()=>{if($("#jarNameInput").value.trim())s.jarName=$("#jarNameInput").value.trim();closeAll();render()}
$("#addChallenge").onclick=()=>open("challenge");$("#saveChallenge").onclick=()=>{let n=$("#challengeName").value.trim(),g=Math.max(1,+$("#challengeGoal").value||1);if(n)s.challenges.push({id:"c"+Date.now(),name:n,goal:g,progress:0});$("#challengeName").value="";closeAll();render()}
function manage(colorMode=false){$("#manageTitle").textContent=colorMode?"star colors":"manage habits";let box=$("#manageList");box.innerHTML="";s.habits.forEach(h=>{let e=document.createElement("div");e.className="manage-row";e.innerHTML=`<div><b>${esc(h.name)}</b>${colorMode?`<input data-col="${h.id}" type="color" value="${h.color}">`:`<small>${esc(h.tiny)}</small>`}</div>${colorMode?"":`<button data-del="${h.id}">delete</button>`}`;box.append(e)});$$("[data-del]").forEach(b=>b.onclick=()=>{s.habits=s.habits.filter(x=>x.id!==b.dataset.del);manage();render()});$$("[data-col]").forEach(i=>i.onchange=()=>{s.habits.find(x=>x.id===i.dataset.col).color=i.value;render()});open("manage")}$("#manageHabits").onclick=()=>manage();$("#starColors").onclick=()=>manage(true)
$("#morning").onchange=e=>{s.settings.morning=e.target.value;save()};$("#evening").onchange=e=>{s.settings.evening=e.target.value;save()};$("#testNotification").onclick=async()=>{if(!("Notification"in window))return alert("Notifications aren't available here.");let p=await Notification.requestPermission();if(p==="granted")new Notification("gold star day ♡",{body:"One tiny thing counts. Your stars are still here."})}
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));picker();render();